services:
  gcli2api:
    build: .
    container_name: gcli2api
    restart: unless-stopped
    ports:
      - "7861:7861"
    environment:
      - PASSWORD=vR4&nL8$
      - PORT=7861
    volumes:
      - /root/docker/gcli2api/data/creds:/app/creds
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 1536M
        reservations:
          cpus: '0.10'
          memory: 256M
